### ISSUE TITLE
editting affiliate/organization data

### ISSUE THREAD

**Issue by TheSwindler44** [Zuluru/Zuluru3#10]
The request has been black-holed

Error: The requested address '/settings/organization?affiliate=2' was not found on this server.
Affiliate/Organization data not modifiable while using admin account to make changes.

I've tried fixing it myself but I think its an issue with the validators.

-------------------------------

Also will there be a way to import bulk users?

**Comment by Zuluru** [comment]
Black-holing is usually a result of a form sitting open for too long before submitting it. Any chance that's the situation here?

The old version of Zuluru had a bulk import function, but it was only used once, for the client that it was developed for, so re-implementing it in v3 has been low priority.

**Comment by TheSwindler44** [comment]
I dont think that is the issue, the form is open no longer than a few minutes before I attempt to submit the data resulting in the black-hole request. 
I removed all the inputs and the data would submit without being black-holed.

Ok, i was just wondering. I've been studying the database structure enough to be able to submit data straight into the tables.

**Comment by TheSwindler44** [comment]
Also could you explain why opening anything other than /game_slots/add?affiliate=1 results in 
An Internal Error Has Occurred
Error: An Internal Error Has Occurred.

For example, i have 39 affiliates registered but anytime i go to /game_slots/add?affiliate=3(any number other then 1) the error is presented.

**Comment by Zuluru** [comment]
I'd need more information (e.g. details from the error log, like a stack trace) to say why that might be happening. It's just the "add game slots" that's causing this particular error? If so, my first guess (without testing) would be that maybe you have no facilities added for those other affiliates.

**Comment by TheSwindler44** [comment]
Every Facility I have has at least two fields under its belt. The error occurs when I choose a specific facility from the navbar under Fields. 

This is the stacktrace from the error.log file:

2019-10-17 20:08:35 Error: [Authorization\Policy\Exception\MissingPolicyException] 
Request URL: /game_slots/add?affiliate=3
Referer URL: /facilities
Stack Trace:
#0 /home/teague14/public_html/team/vendor/cakephp/authorization/src/AuthorizationService.php(53): Authorization\Policy\ResolverCollection->getPolicy(false)
#1 /home/teague14/public_html/team/src/Authentication/ActAsIdentity.php(239): Authorization\AuthorizationService->can(Object(App\Authentication\ActAsIdentity), 'add_game_slots', false)
#2 /home/teague14/public_html/team/vendor/cakephp/authorization/src/Controller/Component/AuthorizationComponent.php(129): App\Authentication\ActAsIdentity->can('add_game_slots', false)
#3 /home/teague14/public_html/team/vendor/cakephp/authorization/src/Controller/Component/AuthorizationComponent.php(68): Authorization\Controller\Component\AuthorizationComponent->_can(false, 'add_game_slots')
#4 /home/teague14/public_html/team/src/Controller/GameSlotsController.php(116): Authorization\Controller\Component\AuthorizationComponent->authorize(false, 'add_game_slots')
#5 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Controller/Controller.php(609): App\Controller\GameSlotsController->add()
#6 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction()
#7 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\GameSlotsController))
#8 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /home/teague14/public_html/team/src/Middleware/AffiliateConfigurationLoader.php(19): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\AffiliateConfigurationLoader->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /home/teague14/public_html/team/src/Http/Middleware/ActAsMiddleware.php(56): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\ActAsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /home/teague14/public_html/team/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php(113): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /home/teague14/public_html/team/src/Application.php(504): Authorization\Middleware\AuthorizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /home/teague14/public_html/team/src/Middleware/LocalizationMiddleware.php(169): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /home/teague14/public_html/team/src/Application.php(439): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 /home/teague14/public_html/team/src/Application.php(405): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 /home/teague14/public_html/team/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php(121): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 /home/teague14/public_html/team/src/Application.php(392): Authentication\Middleware\AuthenticationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#25 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 /home/teague14/public_html/team/vendor/dereuromark/cakephp-ajax/src/Middleware/AjaxMiddleware.php(72): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Ajax\Middleware\AjaxMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 /home/teague14/public_html/team/src/Http/Middleware/CookiePathMiddleware.php(33): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\CookiePathMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Middleware/EncryptedCookieMiddleware.php(89): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\EncryptedCookieMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#32 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#33 /home/teague14/public_html/team/src/Application.php(357): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#34 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#35 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php(135): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#36 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\BodyParserMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#37 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#38 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#39 /home/teague14/public_html/team/vendor/ozee31/cakephp-cors/src/Routing/Middleware/CorsMiddleware.php(32): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#40 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cors\Routing\Middleware\CorsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#41 /home/teague14/public_html/team/src/Middleware/LocalizationMiddleware.php(169): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#42 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#43 /home/teague14/public_html/team/src/Middleware/LocalizationMiddleware.php(169): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#44 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#45 /home/teague14/public_html/team/src/Middleware/ConfigurationLoader.php(19): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#46 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\ConfigurationLoader->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#47 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#48 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#49 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#50 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#51 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#52 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#53 /home/teague14/public_html/team/webroot/index.php(41): Cake\Http\Server->run()
#54 {main}

**Comment by TheSwindler44** [comment]
THANK YOU SO MUCH FOR THE HELP!!!

Here is the stacktrace from the black-hole error I'm still running into:

2019-10-17 20:11:02 Error: [Cake\Http\Exception\BadRequestException] The request has been black-holed
Request URL: /settings/organization?affiliate=2
Referer URL: /settings/organization?affiliate=2
Stack Trace:
#0 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php(195): Cake\Controller\Component\SecurityComponent->_callback(Object(App\Controller\SettingsController), '_blackhole', Array)
#1 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Controller/Component/SecurityComponent.php(127): Cake\Controller\Component\SecurityComponent->blackHole(Object(App\Controller\SettingsController), 'auth', Object(Cake\Controller\Exception\AuthSecurityException))
#2 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Event/EventManager.php(353): Cake\Controller\Component\SecurityComponent->startup(Object(Cake\Event\Event))
#3 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Event/EventManager.php(330): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#4 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(114): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#5 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Controller/Controller.php(675): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#6 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(115): Cake\Controller\Controller->startupProcess()
#7 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\SettingsController))
#8 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /home/teague14/public_html/team/src/Middleware/AffiliateConfigurationLoader.php(19): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\AffiliateConfigurationLoader->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /home/teague14/public_html/team/src/Http/Middleware/ActAsMiddleware.php(56): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\ActAsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /home/teague14/public_html/team/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php(113): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /home/teague14/public_html/team/src/Application.php(504): Authorization\Middleware\AuthorizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /home/teague14/public_html/team/src/Middleware/LocalizationMiddleware.php(169): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 /home/teague14/public_html/team/src/Application.php(439): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 /home/teague14/public_html/team/src/Application.php(405): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 /home/teague14/public_html/team/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php(121): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 /home/teague14/public_html/team/src/Application.php(392): Authentication\Middleware\AuthenticationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#25 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 /home/teague14/public_html/team/vendor/dereuromark/cakephp-ajax/src/Middleware/AjaxMiddleware.php(72): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Ajax\Middleware\AjaxMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#28 /home/teague14/public_html/team/src/Http/Middleware/CookiePathMiddleware.php(33): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#29 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Http\Middleware\CookiePathMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#30 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Middleware/EncryptedCookieMiddleware.php(89): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#31 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\EncryptedCookieMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#32 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php(107): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#33 /home/teague14/public_html/team/src/Application.php(357): Cake\Http\Middleware\CsrfProtectionMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#34 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Application->App\{closure}(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#35 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Middleware/BodyParserMiddleware.php(140): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#36 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Middleware\BodyParserMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#37 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(156): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#38 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#39 /home/teague14/public_html/team/vendor/ozee31/cakephp-cors/src/Routing/Middleware/CorsMiddleware.php(32): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#40 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cors\Routing\Middleware\CorsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#41 /home/teague14/public_html/team/src/Middleware/LocalizationMiddleware.php(169): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#42 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#43 /home/teague14/public_html/team/src/Middleware/LocalizationMiddleware.php(169): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#44 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LocalizationMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#45 /home/teague14/public_html/team/src/Middleware/ConfigurationLoader.php(19): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#46 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\ConfigurationLoader->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#47 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#48 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#49 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#50 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#51 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#52 /home/teague14/public_html/team/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#53 /home/teague14/public_html/team/webroot/index.php(41): Cake\Http\Server->run()
#54 {main}

**Comment by Zuluru** [comment]
Just committed a fix for the game slots problem; regions and facilities need to be set up separately for each affiliate, and it seems this hasn't happened here.

I will have to investigate the settings issue more on the weekend.

**Comment by Zuluru** [comment]
The affiliate settings issue has now also been resolved.
