### ISSUE TITLE
You do not have permission to access that page.

### ISSUE THREAD

**Issue by brianhenson** [Zuluru/Zuluru3#14]
When trying to add questions to the questionnaire, I get You do not have permission to access that page. I am logged in as the only admin user.

**Comment by Zuluru** [comment]
Are you using affiliates, by any chance? There was a similar permission issue with that recently. If not, then the only other things that makes any sense is if your login session timed out or you deleted the questionnaire from a different browser window, but those seem unlikely.

**Comment by brianhenson** [comment]
nope just a standard base install with nothing abnormal turned on. Even went as far as to clear the cache in Z, browser cache and log out and back in again with same result when you search it gives that error

**Comment by Zuluru** [comment]
Can you provide the relevant line(s) from the web server (e.g. Apache) logs that show where it tried to find the question but was rejected? It should mention something about `/questions/autocomplete`.

**Comment by brianhenson** [comment]
nothing in the error logs but this is from the access log

10.20.30.48 - - [11/Dec/2019:03:07:35 +0000] "GET /questionnaires/edit?questionnaire=1 HTTP/1.1" 200 4689 "https://dcsc.brianhenson.tech/questionnaires/view?questionnaire=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
10.20.30.48 - - [11/Dec/2019:03:07:51 +0000] "GET /questions/autocomplete?affiliate=1&term=la HTTP/1.1" 200 807 "https://dcsc.brianhenson.tech/questionnaires/edit?questionnaire=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"

**Comment by Zuluru** [comment]
If anyone else runs into this, the short-term hack is to change line 11 of `src/Policy/AffiliatePolicy.php` to read:

`if ($action != 'autocomplete' && !Configure::read('feature.affiliates')) {`

The long-term fix will come in v3.2, which is nearly done, just awaiting a fix for a translation issue from the CakePHP team.

**Comment by Zuluru** [comment]
Fix for this is in the 3.1.2 release.
