### ISSUE TITLE
Attempting to create legue

### ISSUE THREAD

**Issue by KoreusZ** [Zuluru/Zuluru3#16]
When I hit submit it says Error: an internal error has occurred. I'm running it with PHP 7.3 and MariaDB 10.3.18 on debian.
[error.log](https://github.com/Zuluru/Zuluru3/files/4006784/error.log)

**Comment by Zuluru** [comment]
It hasn't been tested yet on Maria. Should be highly compatible, but it seems from your log that Maria (or at least your installation) has a setting like MySQL's NO_ZERO_IN_DATE or NO_ZERO_DATE enabled. If it's possible to disable that for now, then you should be able to proceed; if not, you'll have to switch to MySQL or else wait for an update that resolves this (which should be coming soon).

**Comment by KoreusZ** [comment]
I have made the specified changes but the problem persists. Here is a fresh log.
[error.log](https://github.com/Zuluru/Zuluru3/files/4007368/error.log)

**Comment by KoreusZ** [comment]
Update, I was able to fix the issue by disabling STRICT_TRANS_TABLES

**Comment by Zuluru** [comment]
Good work! I expect this info will help me to ensure that the update, when it comes, will work on both MySQL and Maria.
