### ISSUE TITLE
Internal Error when deleting an account.

### ISSUE THREAD

**Issue by KoreusZ** [Zuluru/Zuluru3#18]
[error.log](https://github.com/Zuluru/Zuluru3/files/4037151/error.log)

**Comment by KoreusZ** [comment]
I was able to work around this by locking the accounts before deleting them. This makes sense I suppose, but a specific message telling this to the user would be helpful.

**Comment by Zuluru** [comment]
You shouldn't need to lock accounts to delete them. I'll look into what went wrong here when I find some time.

**Comment by Zuluru** [comment]
Looks like this error would only have come up when deleting an administrator. Fixed in the 3.1.2 release.
