### ISSUE TITLE
Zuluru 3.2

### ISSUE THREAD

**Issue by TheSwindler44** [Zuluru/Zuluru3#21]
I'm just curious when the release of the new Zuluru 3.2 version will be available for everyone?

**Comment by Zuluru** [comment]
The last known third-party bug holding up release has been resolved, so there should just a bit more testing to be done. Looking at early February for release!

**Comment by TheSwindler44** [comment]
Great!

**Comment by Zuluru** [comment]
I've just pushed through a number of minor bug fixes and tagged it as version 3.1.2. Final testing on 3.2.0 is ongoing.

**Comment by TheSwindler44** [comment]
Is version 3.2.0 still planned for early February?

**Comment by Zuluru** [comment]
Hopefully, this weekend; maybe the weekend after.

**Comment by Zuluru** [comment]
3.2 is now tentatively released, in the "translation" feature branch. This version may require PHP 7.2, I'm not sure exactly at this time.

**Comment by Zuluru** [comment]
3.2 has been running on a few sites for several weeks now. A few minor issues have been resolved, and the branch has been merged, making 3.2 official now.
