### ISSUE TITLE
Install the new Zuluru Issue.

### ISSUE THREAD

**Issue by TheSwindler44** [Zuluru/Zuluru3#24]
Hello,

I recently got your notification that you posted the big updated however I'm running into an issue with installing the new system. I don't believe the SQL is importing properly after clicking Create Scheme. Then the page reloads with the following error:
`Database Import Failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locale' in 'field list'`

This is a new install that I was gonna test with before migrating the data I've accumulated over from the older version.

Here is my stack trace:
[error.log](https://github.com/Zuluru/Zuluru3/files/4462174/error.log)

The first line at the top is the response when the Create Scheme fails. Any thing after line 1 was generated when I tried visiting the site homepage. Hopefully it is helpful.

**Comment by Zuluru** [comment]
It's challenging at times trying to keep a functional "from scratch" installer while also providing database migrations for people upgrading existing installations. I'll have to look into this and see what's going wrong. If you have shell access and installed via git, though, it should always be possible to update to the latest version with:

- git pull
- composer install
- bin/cake migrations migrate

**Comment by Zuluru** [comment]
Apologies for the delay. I believe that the “bugfix/installation” branch now available should resolve this, and related potential issues. Can you check it out and see if it resolves the issue for you?

**Comment by Zuluru** [comment]
Have heard from a few people that this has resolved the issue, so marking this closed. Branch has been merged into the master.

**Comment by shumailasiddique** [comment]
After following all installation steps when i am trying to access 
https://199-19-74-48.cloud-xip.io/installer/install
i am getting not found error when i am just trying to access main page which is https://199-19-74-48.cloud-xip.io i am getting this error
[Tue Feb 02 05:24:12.670813 2021] [php7:error] [pid 29743] [client 103.255.7.38:46044] PHP Fatal error:  Interface 'Authentication\\AuthenticationServiceProviderInterface' not found in /var/www/html/Zuluru3/src/Application.php on line 55

**Comment by Zuluru** [comment]
From the second error, my first guess is that `composer install` either wasn't run or didn't complete successfully. Can you try running that again and see what output it gives?

**Comment by shumailasiddique** [comment]
i have reinstalled the composer all dependencies were downloaded successfully without giving any error after that when i launch Zlulur at 
https://199-19-74-48.cloud-xip.io/installer/install
it gives url not found when i hit main url which is this 
https://199-19-74-48.cloud-xip.io/
i am getting these errors 
[Wed Feb 03 04:43:58.700007 2021] [php7:notice] [pid 2477] [client 103.255.7.24:11842] PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /var/www/html/Zuluru3/config/bootstrap.php on line 115
[Wed Feb 03 04:43:58.722815 2021] [php7:error] [pid 2477] [client 103.255.7.24:11842] PHP Fatal error:  [Cake\\Database\\Exception\\MissingDriverException] Database driver Cake\\Database\\Driver\\ could not be found.\n#0 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Database/Connection.php(119): Cake\\Database\\Connection->setDriver('Cake\\\\Database\\\\D...', Array)\n#1 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(88): Cake\\Database\\Connection->__construct(Array)\n#2 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(96): Cake\\Datasource\\ConnectionRegistry->_create('Cake\\\\Database\\\\C...', 'default', Array)\n#3 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(204): Cake\\Core\\ObjectRegistry->load('Cake\\\\Database\\\\C...', Array)\n#4 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(241): Cake\\Datasource\\ConnectionManager::get('default')\n#5 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(60): Cake\\ORM\\Locator\\TableLocator->get('Sessions', Array)\n#6 /var/www/html/Zuluru3/vendor in /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 180
[Wed Feb 03 04:43:58.723258 2021] [php7:error] [pid 2477] [client 103.255.7.24:11842] PHP Fatal error:  [Cake\\Database\\Exception\\MissingDriverException] Database driver Cake\\Database\\Driver\\ could not be found.\n#0 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Database/Connection.php(119): Cake\\Database\\Connection->setDriver('Cake\\\\Database\\\\D...', Array)\n#1 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(88): Cake\\Database\\Connection->__construct(Array)\n#2 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(96): Cake\\Datasource\\ConnectionRegistry->_create('Cake\\\\Database\\\\C...', 'default', Array)\n#3 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(204): Cake\\Core\\ObjectRegistry->load('Cake\\\\Database\\\\C...', Array)\n#4 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(241): Cake\\Datasource\\ConnectionManager::get('default')\n#5 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(60): Cake\\ORM\\Locator\\TableLocator->get('Sessions', Array)\n#6 /var/www/html/Zuluru3/vendor in /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 180

**Comment by shumailasiddique** [comment]
i have downgraded mysql to mysql 5.7 still i am facing these issues

**Comment by Zuluru** [comment]
There's a bit in the Troubleshooting section of the README about time zone issues.

**Comment by shumailasiddique** [comment]
what about connection issues my mysql username is shali and pass is test_pw9 so what should i change in docker file to connect to database

**Comment by Zuluru** [comment]
Those details are all specified through the web-based installer process, once you can get that to run.

**Comment by shumailasiddique** [comment]
can you give any idea about why i am getting these fatal errors obviously i will get that installation process when i fix these fatal errors 
[Wed Feb 03 04:43:58.722815 2021] [php7:error] [pid 2477] [client 103.255.7.24:11842] PHP Fatal error: [Cake\Database\Exception\MissingDriverException] Database driver Cake\Database\Driver\ could not be found.\n#0 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Database/Connection.php(119): Cake\Database\Connection->setDriver('Cake\\Database\\D...', Array)\n#1 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(88): Cake\Database\Connection->__construct(Array)\n#2 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(96): Cake\Datasource\ConnectionRegistry->_create('Cake\\Database\\C...', 'default', Array)\n#3 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(204): Cake\Core\ObjectRegistry->load('Cake\\Database\\C...', Array)\n#4 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(241): Cake\Datasource\ConnectionManager::get('default')\n#5 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(60): Cake\ORM\Locator\TableLocator->get('Sessions', Array)\n#6 /var/www/html/Zuluru3/vendor in /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 180
[Wed Feb 03 04:43:58.723258 2021] [php7:error] [pid 2477] [client 103.255.7.24:11842] PHP Fatal error: [Cake\Database\Exception\MissingDriverException] Database driver Cake\Database\Driver\ could not be found.\n#0 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Database/Connection.php(119): Cake\Database\Connection->setDriver('Cake\\Database\\D...', Array)\n#1 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionRegistry.php(88): Cake\Database\Connection->__construct(Array)\n#2 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(96): Cake\Datasource\ConnectionRegistry->_create('Cake\\Database\\C...', 'default', Array)\n#3 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Datasource/ConnectionManager.php(204): Cake\Core\ObjectRegistry->load('Cake\\Database\\C...', Array)\n#4 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php(241): Cake\Datasource\ConnectionManager::get('default')\n#5 /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Http/Session/DatabaseSession.php(60): Cake\ORM\Locator\TableLocator->get('Sessions', Array)\n#6 /var/www/html/Zuluru3/vendor in /var/www/html/Zuluru3/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 180

**Comment by shumailasiddique** [comment]
ok let me explain what steps i have done 
1installed composer with 
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
2)git clone  https://github.com/Zuluru/Zuluru3.git
cd Zuluru3
composer install
All composer dependencies were installed successfully in Zuluru3/vendor
3)HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
setfacl -R -m u:${HTTPDUSER}:rwx tmp logs upload
setfacl -R -d -m u:${HTTPDUSER}:rwx tmp logs upload
4)Configure web server (Apache,) to point at Zuluru3/webroot in my /etc/apache2/sites-available/default-ssl.conf
5)made small change in docker-compose.yml changed port to 
ports:
      - "8084:80"
because with port 80:80 i was getting port error then i run this command 
docker-compose pull && docker-compose up -d
that command run successfully 
6)as my main domain url is https://199-19-74-48.cloud-xip.io/
when i am trying to open installer with 
https://199-19-74-48.cloud-xip.io/installer/install
i am getting url not found error when i am opening main url which is 
https://199-19-74-48.cloud-xip.io/ i am getting all those errors

**Comment by shumailasiddique** [comment]
i have renamed config/.env file to .env_test2 but still i am getting all those errors

**Comment by shumailasiddique** [comment]
i am not able to reach to that installation process i am getting url not found when i hit 
https://199-19-74-48.cloud-xip.io/ installer/install

**Comment by shumailasiddique** [comment]
ok after changing installation url to 
https://199-19-74-48.cloud-xip.io/index.php/installer/install i am geeting following page where cakephp app instaler and togglenavigation are not clickable 
![12](https://user-images.githubusercontent.com/46244940/106785042-d0c5ed00-666e-11eb-90b4-a898e7166e4e.PNG)

**Comment by shumailasiddique** [comment]
ok after adding index.php in url i was able to open installer at 
https://199-19-74-48.cloud-xip.io/index.php/installer/install
after entering database connection credentials which are 
localhost,username:shali,pass:test,database:zuluru
i got this 500
![14](https://user-images.githubusercontent.com/46244940/106790475-70867980-6675-11eb-915a-7702d849fdf8.PNG)
 page which i am attaching in attachment my zuluru database is empty yet

**Comment by Zuluru** [comment]
The details of what caused that error 500 should be in the `logs/error.log` file.

**Comment by shumailasiddique** [comment]
after solving timezone error i was able to solve intel 500 error but now the new error is when i click create schema i am getting this error 
![15](https://user-images.githubusercontent.com/46244940/106837967-3b9e1500-66bd-11eb-9dc4-b8c266af9570.PNG)

**Comment by Zuluru** [comment]
What is in the the `config/Migrations` folder? There should be a bunch of files there named by timestamps, of which this is one.

**Comment by shumailasiddique** [comment]
here is content of config/Migrations there is no such file with that timestamp 
![16](https://user-images.githubusercontent.com/46244940/106843158-3219aa80-66c7-11eb-800f-6b743b603980.PNG)

**Comment by shumailasiddique** [comment]
here is content of oldmigrations folder 
![17](https://user-images.githubusercontent.com/46244940/106843257-6ee5a180-66c7-11eb-8706-1acf3f57617c.PNG)

**Comment by Zuluru** [comment]
Looks like you've used the fixture factories branch, which is not yet ready for general use, instead of the master branch?

**Comment by shumailasiddique** [comment]
Thanks for your continuous support i was mistakenly using fixture factory branch after switching back to master branch when i clicked create schema 85 tables were imported in the database but i faces this error at the end of create schema 
![18](https://user-images.githubusercontent.com/46244940/106849255-313b4580-66d4-11eb-9355-7c34bed9abee.PNG)

**Comment by Zuluru** [comment]
You said you're using MySQL 5.7. But 5.7.what? The comment [here](https://github.com/Zuluru/Zuluru3/issues/4#issuecomment-473411090) about 5.7.5 and later still applies. (The PHP7 comment does not; it's fully compatible to at least 7.3.)

**Comment by shumailasiddique** [comment]
mysql version is 5.7.33 and php version is  7.3.26-1

**Comment by shumailasiddique** [comment]
i have upgraded mysql to mysql  8.0.23  and run installation again i am facing same error again after importing 85 tables

**Comment by shumailasiddique** [comment]
ok after changing sql mod that issue was fixed and i see this message 
Your admin password has been set to UuJyTPrUKyVd6uygL. Log in right away and change it to something more memorable.
Database imported
now my question is that is the installation process complete ?and can i point apache to /var/www/html from /var/www/html/Zuluru3/webroot now ?
because when i am accessing 
https://199-19-74-48.cloud-xip.io/ now it redirects to 
https://199-19-74-48.cloud-xip.io/users/login?redirect=%2F
 which gives url not found error

**Comment by shumailasiddique** [comment]
after changing apache to point to /var/www/html 
and access https://199-19-74-48.cloud-xip.io/Zuluru3/
it redirects to 
https://199-19-74-48.cloud-xip.io/Zuluru3/users/login?redirect=%2F
which gives url not found error here is my env fi
le content 
#!/usr/bin/env bash
# Used as a default to seed config/.env which enables you to use environment
# variables to configure the aspects of your application that vary by
# environment. This provides a simpler development workflow over standard
# environment variables.
#
# To use this file, first copy it into `config/.env`. In typical scenarios,
# this is best done by visiting the /installer URL in your browser. See
# README.md for installation details.

########################
# System settings
########################

# Setting this to true puts the system into debug mode, which can help to
# diagnose installation errors. This should always be the first thing to try
# if you are getting the "white screen of death". However, error messages
# that it will display can give away information about your system setup to
# potential attackers, plus it will slow down operations, so it should never
# be used in a production environment.
export DEBUG="false"

# This must be set to the base URL of your site, without a trailing slash.
# This will be used in things like system-generated emails.
export SITE_BASE_URL="https://199-19-74-48.cloud-xip.io"

# See http://ca3.php.net/timezones for a list of valid timezone names. You
# may need to follow the instructions from
# http://dev.mysql.com/doc/refman/5.7/en/mysql-tzinfo-to-sql.html
# to make all timezone names available.
export TIMEZONE="UTC"

# The default locale for translation, formatting currencies and numbers, date
# and time.
export APP_DEFAULT_LOCALE="en_US"

# This is the generic word to be used for all field-type spaces that the
# site will deal with. If you offer ultimate, volleyball and hockey, you
# will need to find something that conveys "field, court or rink". Perhaps
# "location"?
export FIELD_NAME="field"

# For proper security, this MUST be set to a long, random string of bytes.
# It is recommended to use at least 32 bytes. NOTE: If you ever change this
# after users are registered, everyone will need to do a password reset, so
# be sure to set it right away! This handy link will give you two random 20
# character strings you can paste together to get a nice 40 character salt:
# https://www.random.org/strings/?num=2&len=20&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new
export SECURITY_SALT="ln5rAe0sSxMSDbXWlzwoHkppalteTFiyVhXNJUph"

########################
# Email settings
########################

# Setting this to true will prevent any emails from actually being sent,
# instead dumping them to the screen for inspection. This is purely a
# debugging tool, never intended for production environments.
export DEBUG_EMAIL="false"

# For optimal deliverability, bounce handling, etc. it is recommended
# to use the Smtp transport. If you do, you MUST provide the username,
# password and host, and may also need to change the port and other settings.
# If Smtp is not an option for you, you can use the 'Mail' transport (set
# this in the "EMAIL_TRANSPORT" field), in which case the SMTP fields can
# be ignored or deleted from here, but you will then need to set the
# "EMAIL_FROM" address.
export EMAIL_TRANSPORT="Mail"
export SMTP_HOST="smtp.example.com"
export SMTP_PORT="587"
export SMTP_USERNAME=""
export SMTP_PASSWORD=""
export SMTP_TLS="false"
export EMAIL_FROM="you@localhost"

########################
# Database settings
########################

# Setting this to true will cause all SQL queries to be logged. This slows
# execution substantially and should only be used for debugging, never on
# production environments.
export DEBUG_SQL_LOG="true"

# Set the driver to use for your database. To date, Zuluru has only been
# tested on MySQL, but should be close to functional on MSSQL (Sqlserver).
# For other database options, check CakePHP documentation or contact
# admin@zuluru.org.
export SQL_DRIVER="Mysql"

# Set the connection details for your database configuration here. If the
# port is left blank, Zuluru will use the default DB port based on the driver
# selected. If your installation uses a non-standard port, you will need to
# set it here.
export SQL_HOSTNAME="localhost"
export SQL_PORT=""
export SQL_USERNAME="shali"
export SQL_PASSWORD="Test_pw9"
export SQL_DATABASE="zuluru"

# If you want to run Zuluru's unit tests, you'll need to create a second
# database and set those details here. This is a development thing; if you're
# just running Zuluru as an application, you can leave these alone.
export SQL_TEST_HOSTNAME="{default_host}"
export SQL_TEST_PORT=""
export SQL_TEST_USERNAME=""
export SQL_TEST_PASSWORD=""
export SQL_TEST_DATABASE=""

########################
# Logging settings
########################

# Uncomment these to define logging configuration via environment variables.
# Add levels[]=notice&levels[]=info&levels[]=debug& here for additional levels of logging.
#export LOG_DEBUG_URL="file://logs?levels[]=notice&levels[]=info&levels[]=debug&file=debug"
#export LOG_ERROR_URL="file://logs?levels[]=warning&levels[]=error&levels[]=critical&levels[]=alert&levels[]=emergency&file=error"

**Comment by shumailasiddique** [comment]
i am able to access login url with 
https://199-19-74-48.cloud-xip.io/index.php/users/login?redirect=%2F
how can i remove that index.php from url?

**Comment by shumailasiddique** [comment]
ok i should mention it here hopefully it will help someone later on i enabled rewrite mode in ubuntu server to handle that broken url issue app installed successfully thanks for the support :)

**Comment by Zuluru** [comment]
Sounds like it's all working now? Or is there still some outstanding problem?

**Comment by shumailasiddique** [comment]
I haven't done complete testing yet but basic installation has been done

**Comment by shumailasiddique** [comment]
while running cron job command i am getting this error 
![22](https://user-images.githubusercontent.com/46244940/107179938-87242c00-69f9-11eb-8818-03a3ae3b4d06.PNG)

**Comment by shumailasiddique** [comment]
ok i have fixed cron job issue changing permission to bin/cake and that mysql error with creating team , league and adding team to a league

**Comment by Zuluru** [comment]
It looks like there's a bug when it tries to do league-related tasks but there are no leagues. I'll aim to get that fixed soon, but in the meantime you should be able to create a new league, I would expect, and then all the rest should work fine.
