### ISSUE TITLE
Individual statistics question

### ISSUE THREAD

**Issue by cameroneickmeyer** [Zuluru/Zuluru3#28]
What is the best way to display the individual statistics for players? Is there a specific plugin?

**Comment by Zuluru** [comment]
Statistics are built-in, but need to be enabled on a per-league basis. Each sport will have a set of stats that can be enabled, some are stats that need to be entered after each game, some are calculated automatically (e.g. wins) for each game, and some are season totals across all the games. League, game and team stats pages show the stats for all relevant players.

**Comment by cameroneickmeyer** [comment]
How do I enable them at the league level?

**Comment by Zuluru** [comment]
You first have to enable the stat tracking feature under Configuration -> Scoring. Then, the league edit page will have an option for whether to collect stats. If you set that to any of the options that turn it on, you'll get a list of stats to choose from.
