### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [Zuluru/Zuluru3#5]
Hello, i am a graphic designer who loves to contribute logos to open source projects. Do you need a logo for this project or any of your other projects?

**Comment by Zuluru** [comment]
I think I'm okay with the current logo. I would at some point love to get a fresh set of icons, but there's quite a lot of them and I feel like that's maybe more time than you would want to invest. Also, I know icon design and logo design are different things, so perhaps not your expertise.
